Project1
della-padula/YappUltraHardPractice pull request #122
Opened 2021-09-29 00:41 UTC by ITlearning

2021-09-29 00:58 UTC, SH4CK3RS commented on UltraProject1/UltraProject1/Functions/KakaoAuthManager.swift
> +
```swift
private init() { } // 싱글톤 이외의 초기화를 막기 위함. 
```
싱글톤(shared)을 사용하므로 별도로 초기화 할일이 없음

2021-09-29 00:59 UTC, SH4CK3RS commented on UltraProject1/UltraProject1/AppDelegate.swift
> +
위으; KakaoSDKCommon init하는 부분을 별도의 method로 빼는게 보기 더 좋을듯함
```swift
private func initKakaoSDK() {
        if let infoDic: [String: Any] = Bundle.main.infoDictionary {
            if let info = infoDic["CFBundleURLTypes"] as? [Any],
            let dic = info[0] as? NSDictionary,
            let key = dic.value(forKey: "CFBundleURLSchemes") as? [String] {
                let str = key[0]
                let startIdx: String.Index = str.index(str.startIndex, offsetBy: 5)
                KakaoSDKCommon.initSDK(appKey: String(str[startIdx...]))
            }
        }
    }
```

2021-09-29 01:01 UTC, SH4CK3RS commented on UltraProject1/UltraProject1/ViewControllers/LoginViewController.swift
> +            $0.top.equalToSuperview().inset(120)
$0.top.equalToSuperview().inset(120) -> $0.top.equalTo(120)으로도 사용 가능
아래도 마찬가지 $0.left.equalTo(24)

2021-09-29 01:01 UTC, della-padula requested changes

2021-09-29 01:01 UTC, della-padula commented on UltraProject1/UltraProject1/ViewControllers/ResultViewController.swift
> +        if !isRecordVC() {
이렇게 분기하는게 아닌 ViewController 초기화 시 관련 프로퍼티 값을 설정함으로써 처리할 수 있습니다.

2021-09-29 01:07 UTC, SH4CK3RS commented on UltraProject1/UltraProject1/ViewControllers/MainViewController.swift
> +
navigationController?.isNavigationBarHidden = true 를 이대로만 사용하게 되면 다음 뷰(push된)컨트롤러에서 스와이프로 pop할 경우 부자연스러운 인터렉션이 발생하게됨
navigationController?.setNavigationBarHidden(animated, animated: true)를 활용하는것을 추천(다음 씬에서도 수정하세요)

2021-09-29 01:10 UTC, della-padula requested changes

2021-09-29 01:10 UTC, della-padula commented on UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
> +    var randomNumberShared: Int?
randomNumberShared 네이밍이 조금 이상합니다. 수정해주세요

2021-09-29 01:10 UTC, della-padula commented on UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
> +    var wrongNumber: Int = 0
private으로 변경해주세요

2021-09-29 01:10 UTC, della-padula commented on UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
> +    var count: Int = 0
private으로 변경해주세요

2021-09-29 01:13 UTC, ITlearning commented on UltraProject1/UltraProject1/AppDelegate.swift
> +
수정완료

2021-09-29 01:13 UTC, ITlearning commented on UltraProject1/UltraProject1/ViewControllers/LoginViewController.swift
> +            $0.top.equalToSuperview().inset(120)
수정완료

2021-09-29 01:13 UTC, sanghee-dev commented on UltraProject1/UltraProject1/ViewControllers/ResultViewController.swift
> +        if !isRecordVC() {
수정하였습니다 !!

2021-09-29 01:13 UTC, ITlearning commented on UltraProject1/UltraProject1/Cells/ScoreTableViewCell.swift
> +        scoresLabel.snp.makeConstraints {
수정완료

2021-09-29 01:13 UTC, ITlearning commented on UltraProject1/UltraProject1/Cells/ScoreTableViewCell.swift
> +    private let scoresLabel: UILabel = {
수정완료

2021-09-29 01:14 UTC, ITlearning commented on UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
> +    var coreData: [Score] = []
미처 기입하지 못하였습니다. 수정완료.

2021-09-29 01:14 UTC, SH4CK3RS commented on UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
> +        guard let unwrappedRandomNumberShared = randomNumberShared else { return }
이미 위에서 randomNumber를 생성하여 대입했으므로, 이 값을 사용하기 위해 randomNumberShared를 별도로 언래핑 할 필요가 없음
```swift
selectNumberLabel.text = "\(randomNumber)" // 그대로 사용
```

2021-09-29 01:14 UTC, ITlearning commented on UltraProject1/UltraProject1/Functions/KakaoAuthManager.swift
> +
수정완료.

2021-09-29 01:15 UTC, sanghee-dev commented on UltraProject1/UltraProject1/ViewControllers/MainViewController.swift
> +
수정하였습니다!

2021-09-29 01:16 UTC, della-padula requested changes

2021-09-29 01:16 UTC, della-padula commented on UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
> +            $0.leading.equalTo(view.safeAreaLayoutGuide.snp.leading).offset(10)
leading, trailing 은 safeLayout 을 직접 사용할 필요가 없어보입니다. equalToSuperview로도 충분할 듯

2021-09-29 01:16 UTC, della-padula commented on UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
> +        } else if numbers[indexPath.row] == unwrappedRandomNumberShared {
unwrapping을 두 번 할 필요는 없어보여요

2021-09-29 01:18 UTC, SH4CK3RS commented on UltraProject1/UltraProject1/Cells/GameCollectionViewCell.swift
> +    var settingLabel: Int? {
해당 변수명은 자칫 ViewComponent 자체로 인식될 수 있음. 네이밍을 달리하도록 하면 좋을듯
ex) 
```swift
var number: Int? {
        didSet {
            guard let setting = number else { return }
            numberLabel.text = "\(setting)"
        }
    }
```

2021-09-29 01:19 UTC, sanghee-dev commented on UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
> +    var count: Int = 0
수정하였습니다 !

2021-09-29 01:19 UTC, SH4CK3RS requested changes
코멘트 참고해서 수정해주세요

2021-09-29 01:19 UTC, sanghee-dev commented on UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
> +            $0.leading.equalTo(view.safeAreaLayoutGuide.snp.leading).offset(10)
수정하였습니다!

2021-09-29 01:23 UTC, sanghee-dev commented on UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
> +            $0.leading.equalTo(view.safeAreaLayoutGuide.snp.leading).offset(10)
수정하였습니다!

2021-09-29 01:28 UTC, sanghee-dev commented on UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
> +    var wrongNumber: Int = 0
수정하였습니다 !

2021-09-30 02:06 UTC, glossyyoon commented on UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
> +        view.addSubview(GameViewController.timerLabel)
수정완료, 새로운 변수를 만들었습니다.

2021-09-30 02:06 UTC, glossyyoon commented on UltraProject1/UltraProject1/ViewControllers/MainViewController.swift
> +        logoFinishLabel.snp.makeConstraints {
수정 완료

2021-09-30 02:14 UTC, glossyyoon commented on UltraProject1/UltraProject1/ViewControllers/ResultViewController.swift
> +        view.addSubview(resultTitleLabel)
적용했습니다.

2021-09-30 02:15 UTC, glossyyoon commented on UltraProject1/UltraProject1/ViewControllers/ResultViewController.swift
> +        homeButton.snp.makeConstraints {
수정완료

2021-09-30 02:15 UTC, glossyyoon commented on UltraProject1/UltraProject1/ViewControllers/ResultViewController.swift
> +        failCountLabel.snp.makeConstraints {
수정완료

2021-09-30 02:15 UTC, glossyyoon commented on UltraProject1/UltraProject1/ViewControllers/ResultViewController.swift
> +        secondTryCountLabel.snp.makeConstraints {
수정완료

2021-09-30 02:15 UTC, glossyyoon commented on UltraProject1/UltraProject1/ViewControllers/ResultViewController.swift
> +        firstTryCountLabel.snp.makeConstraints {
수정완료

2021-09-30 02:16 UTC, glossyyoon commented on UltraProject1/UltraProject1/ViewControllers/ResultViewController.swift
> +        resultScoreLabel.snp.makeConstraints {
수정완료

2021-09-30 02:38 UTC, sanghee-dev commented on UltraProject1/UltraProject1/Cells/GameCollectionViewCell.swift
> +    var settingLabel: Int? {
수정하였습니다 !

2021-09-30 08:04 UTC, ITlearning commented on UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
> +        guard let unwrappedRandomNumberShared = randomNumberShared else { return }
두번 언래핑 제거 했습니다.

2021-09-30 08:05 UTC, ITlearning commented on UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
> +            $0.leading.equalTo(view.safeAreaLayoutGuide.snp.leading).offset(10)
수정 완료했습니다 :)

2021-09-30 08:06 UTC, ITlearning commented on UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
> +        } else if numbers[indexPath.row] == unwrappedRandomNumberShared {
수정 완료 했습니다 :)

2021-09-30 09:14 UTC, sanghee-dev commented on UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
> +    var randomNumberShared: Int?
수정하였습니다 !

2021-09-30 09:16 UTC, sanghee-dev commented on UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
> +        guard let unwrappedRandomNumberShared = randomNumberShared else { return }
수정하였습니다 !

2021-09-30 09:19 UTC, sanghee-dev commented on UltraProject1/UltraProject1/ViewControllers/GameViewController.swift
> +            $0.leading.equalTo(view.safeAreaLayoutGuide.snp.leading).offset(10)
수정했습니다 !

2021-10-02 14:19 UTC, merged