Personal/sanghee 2
della-padula/YappUltraHardPractice pull request #140
Opened 2021-09-30 23:53 UTC by sanghee-dev

2021-10-01 20:05 UTC, della-padula requested changes
수고많이하셨습니다

2021-10-01 20:05 UTC, della-padula commented on Sanghee/Practice2/Practice2/Extension/MKMapView+Zoom.swift
> +        if(show) {
() 제거해주세요. 혹시 구글에 이런 코드가 있던 건가요?

2021-10-01 20:05 UTC, della-padula commented on Sanghee/Practice2/Practice2/Extension/UIView+anchor.swift
> +    }
신박하긴 한데.. NSLayoutConstraint의 Extension으로 구현하면 모를까 그렇게 좋아보이지는 않습니다. 만약 업데이트를 해야한다고 할 경우 어떻게 처리할 생각이신가요?

2021-10-01 20:05 UTC, della-padula commented on Sanghee/Practice2/Practice2/Utility/LocationManager.swift
> +    var manager: CLLocationManager = CLLocationManager()
private이 아닌 이유가무엇인가요?

2021-10-01 20:05 UTC, della-padula commented on Sanghee/Practice2/Practice2/Utility/LocationManager.swift
> +    var location: CLLocation?
여기도요

2021-10-02 08:07 UTC, sanghee-dev commented on Sanghee/Practice2/Practice2/Utility/LocationManager.swift
> +    var manager: CLLocationManager = CLLocationManager()
수정하였습니다 !

2021-10-02 08:12 UTC, sanghee-dev commented on Sanghee/Practice2/Practice2/Utility/LocationManager.swift
> +    var location: CLLocation?
수정하였습니다 !!

2021-10-02 08:22 UTC, sanghee-dev commented on Sanghee/Practice2/Practice2/Extension/MKMapView+Zoom.swift
> +        if(show) {
수정하였습니다!

2021-10-02 11:25 UTC, sanghee-dev commented on Sanghee/Practice2/Practice2/Extension/UIView+anchor.swift
> +    }
업데이트시 시스템에게 constaints를 갱신하도록 호출하는 코드를 추가해 수정하였습니다 !

2021-10-02 14:19 UTC, merged