앱스토어 클론
della-padula/YappUltraHardPractice pull request #150
Opened 2021-10-04 15:24 UTC by sanghee-dev

### 관련 이슈
- #143
- #144 
- #145 

### 애니메이션 상세 내용
- 커스텀 애니메이터 생성
- 메인 화면 -> 디테일 화면시 선택한 셀이 디테일의 상단에 위치함(아래 화면 참조)
- 디테일 화면 -> 메인 화면시 기존 위치로 이동하는 듯이 보여짐
  - 메인 화면에서 셀 선택시 뷰 기준 해당 셀의 y값을 저장함

### 메인 화면
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/61302874/135878822-d4204444-979d-4939-bfcb-c52b5831b071.gif)

### 애니메이션 전환
![ezgif com-gif-maker](https://user-images.githubusercontent.com/61302874/135878581-901670a1-ca91-4f71-99a6-f5c15a5ffe40.gif)

2021-10-04 21:27 UTC, della-padula commented
앱스토어는 상세 화면에서 아래로 스크롤하면서 점점 밖으로 벗어나게 되는데 이 부분 구현 안되어 있네요. 구현하고 다시 올리세요. (코드는 어디서 가져온 건 아니죠?)

2021-10-04 21:28 UTC, della-padula requested changes
앱스토어는 상세 화면에서 아래로 스크롤하면서 점점 밖으로 벗어나게 되는데 이 부분 구현 안되어 있네요. 구현하고 다시 올리세요. (코드는 어디서 가져온 건 아니죠?)

2021-10-05 08:42 UTC, sanghee-dev commented
> 앱스토어는 상세 화면에서 아래로 스크롤하면서 점점 밖으로 벗어나게 되는데 이 부분 구현 안되어 있네요. 구현하고 다시 올리세요. (코드는 어디서 가져온 건 아니죠?)

직접 작성하였습니다! 상세 화면 스크롤부분 구현 추가하겠습니다 !

2021-10-05 16:13 UTC, sanghee-dev commented
### 메인 화면
![메인 화면 스크롤](https://user-images.githubusercontent.com/61302874/136061569-59583214-1d5f-4387-b24b-89c5c205946f.gif)

### 디테일 화면
![디테일 화면 스크롤](https://user-images.githubusercontent.com/61302874/136061646-4104d19c-41ee-4e4f-a7fa-77c55b7665a0.gif)

### 애니메이션(cancel 버튼 클릭)
![캔슬 버튼 애니메이션](https://user-images.githubusercontent.com/61302874/136061677-4342d62b-4c5c-4430-bcb1-eeabf8b676cb.gif)

### 애니메이션 2(위로 당김)
![위로 스크롤 애니메이션](https://user-images.githubusercontent.com/61302874/136061698-47ed6278-2153-42b5-9647-d64c03083097.gif)

2021-10-10 12:25 UTC, della-padula requested changes
특별한 것 보다는 개행 처리와 공백 처리에 대해서 명확한 기준을 파악하지 못한 것 같네요.

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/Cell/MainCollectionCell.swift
> +        let mainUnitView = MainUnitView()
이거 초기화 코드가 밖이 아닌 여기에 위치한 이유가 있나요?

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/Function/PopAnimator.swift
> +        if let fromView = fromView {
공백 넣어주세요

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/DetailUnitView.swift
> +    private let titleLabel: UILabel = {
프로퍼티 간 개행 처리

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/DetailUnitView.swift
> +    private let emojiLabel: UILabel = {
프로퍼티 간 개행 처리

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/DetailUnitView.swift
> +    private let paragraphLabel: UILabel = {
프로퍼티 간 개행 처리

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/DetailUnitView.swift
> +        titleLabel.text = detailUnit?.title
if let 이나 guard let으로 옵셔널 체이닝 해주세요

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/DetailUnitView.swift
> +        titleLabel.snp.makeConstraints {
개행

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/DetailUnitView.swift
> +        emojiLabel.snp.makeConstraints {
개행

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/DetailUnitView.swift
> +        paragraphLabel.snp.makeConstraints {
개행

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/DetailViewController.swift
> +    private let mainUnitView = MainUnitView()
개행

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/DetailViewController.swift
> +        cell.detailUnit = mainUnit?.detailUnits[indexPath.row]
mainUnit이 nil일 경우에는 올바른 값이 안들어갈텐데 옵셔널 체이닝 추가해주세요.

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/DetailViewController.swift
> +        deleteBtn.snp.makeConstraints {
개행

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/MainUnitView.swift
> +    private let titleLabel: UILabel = {
개행

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/MainUnitView.swift
> +    private let subTitleLabel: UILabel = {
개행

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/MainUnitView.swift
> +    private let emojiLabel: UILabel = {
개행

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/MainUnitView.swift
> +        subTitleLabel.snp.makeConstraints {
개행

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/MainUnitView.swift
> +        titleLabel.snp.makeConstraints {
개행

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/MainUnitView.swift
> +        emojiLabel.snp.makeConstraints {
개행

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/MainViewController.swift
> +        titleLabel = {
개행

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/MainViewController.swift
> +        profileImageView = {
개행

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/MainViewController.swift
> +        titleLabel.snp.makeConstraints {
개행

2021-10-10 12:25 UTC, della-padula commented on Sanghee/Practice3/Practice3/View/MainViewController.swift
> +        profileImageView.snp.makeConstraints {
개행

2021-10-11 12:58 UTC, sanghee-dev commented on Sanghee/Practice3/Practice3/View/DetailUnitView.swift
> +    private let emojiLabel: UILabel = {
추가하였습니다 !

2021-10-11 13:01 UTC, sanghee-dev commented on Sanghee/Practice3/Practice3/View/DetailViewController.swift
> +        deleteBtn.snp.makeConstraints {
수정하였습니다 !

2021-10-11 13:02 UTC, sanghee-dev commented on Sanghee/Practice3/Practice3/View/MainUnitView.swift
> +    private let titleLabel: UILabel = {
수정하였습니다 !

2021-10-11 13:03 UTC, sanghee-dev commented on Sanghee/Practice3/Practice3/View/DetailUnitView.swift
> +    private let titleLabel: UILabel = {
수정하였습니다 !

2021-10-11 13:09 UTC, sanghee-dev commented on Sanghee/Practice3/Practice3/Cell/MainCollectionCell.swift
> +        let mainUnitView = MainUnitView()
실수로 함수 안에 넣은 것 같습니다 ㅠㅠ 저렇게 작성된 다른 파일도 수정하였습니다 !!

2021-10-16 06:27 UTC, merged