Feature/byeongyun 3
della-padula/YappUltraHardPractice pull request #153
Opened 2021-10-08 11:49 UTC by ITlearning

2021-10-10 12:29 UTC, della-padula requested changes
MVP 구조가 제대로 적용되지 않았습니다. MVP에 대해서 다시 공부하고 수정해주세요.
Presenter에 UI요소가 존재하서는 안됩니다.

Presenter에서는 import UIKit을 제거해야 합니다.

2021-10-10 12:29 UTC, della-padula commented on Byeongyun/Practice3/Practice3/Cell/MainCollectionViewCell.swift
> +import SnapKit
import문 순서 정렬

2021-10-10 12:29 UTC, della-padula commented on Byeongyun/Practice3/Practice3/View/MainViewController.swift
> +    private let cellId = "MainCell"
이 값이 왜 여기에 있을까요?

2021-10-10 12:29 UTC, della-padula commented on Byeongyun/Practice3/Practice3/Cell/MainCollectionViewCell.swift
> +    let cellId = "MainCell"
static 이 아닌 이유는??

2021-10-10 12:29 UTC, della-padula commented on Byeongyun/Practice3/Practice3/Cell/MainCollectionViewCell.swift
> +    private let presenter = Presenter()
cell에 Presenter가 있을 필요가 있을까요?

2021-10-10 12:29 UTC, della-padula commented on Byeongyun/Practice3/Practice3/Cell/MainCollectionViewCell.swift
> +    let cellImageView: UIImageView = {
셀 내부 뷰는 외부에서 접근하지 않도록 막아주세요

2021-10-10 12:29 UTC, della-padula commented on Byeongyun/Practice3/Practice3/Cell/MainCollectionViewCell.swift
> +    private let cellSubLabel: UILabel = {
개행 추가

2021-10-10 12:29 UTC, della-padula commented on Byeongyun/Practice3/Practice3/Presenter/Presenter.swift
> +    private let cellId = "MainCell"
Presenter에는 View와 관련된 코드는 다 배제되어야 합니다. 수정해주세요.
View와 관련된 코드는 View에만, Presenter는 로직 처리만 있어야 합니다.

2021-10-12 00:46 UTC, SH4CK3RS commented on Byeongyun/Practice3/Practice3/Model/Model.swift
> +}
여기에서는 모델을 정의했다기보다는 더미데이터를 여러개 만들었다고 보임
셀에서 사용되는 데이터를 모델로 정의
ex) 
```swift
struct StoreData {
  let image: UIImage
  let mainTitle: String
  let subTitle: String
}
```
이후 이 모델에 데한 더미데이터를 구성할 때 (static으로 구성해도 되고, 별도로 배열을 동적으로 생성하여 추가해줘도 됨)

2021-10-12 01:01 UTC, SH4CK3RS commented on Byeongyun/Practice3/Practice3/View/MainViewController.swift
> +            $0.trailing.equalTo(view.safeAreaLayoutGuide.snp.trailing)
이렇게도 가능함
```swift
$0.top.leading.trailing.equalTo(view.safeAreaLayoutGuide)
```

2021-10-23 00:23 UTC, merged