공지사항 앱 목록 및 상세 화면
della-padula/YappUltraHardPractice pull request #48
Opened 2021-09-17 05:32 UTC by sanghee-dev

2021-09-17 10:54 UTC, della-padula requested changes
수정해주세요

2021-09-17 14:16 UTC, sanghee-dev reviewed
수정하였습니다

2021-09-17 23:04 UTC, della-padula requested changes
많이 고쳐져서 좋습니다 추가로 몇개 더 남겨드리니 수정해주시면 Merge 할게요

2021-09-17 23:04 UTC, della-padula commented on Sanghee/Practice1/Practice1/DetailController.swift
> +import UIKit
import 오름차순으로 정렬해주세요

2021-09-17 23:04 UTC, della-padula commented on Sanghee/Practice1/Practice1/DetailController.swift
> +        DispatchQueue.main.async {
DispatchQueue를 안쓰면 문제가 발생하나요?

2021-09-17 23:04 UTC, della-padula commented on Sanghee/Practice1/Practice1/DetailController.swift
> +        } completion: { _ in
completion 타입 Optional 이지 않나요? Optional이라면 nil로 넣으면 될 것 같습니다.

2021-09-17 23:04 UTC, della-padula commented on Sanghee/Practice1/Practice1/DetailController.swift
> +        cell.contentView.isUserInteractionEnabled = false
cell에서 contentView에 addSubview하면 자동으로 사용자 Interaction은 받아줄 것 같은데... 안돼서 추가한 코드인가요?

2021-09-17 23:04 UTC, della-padula commented on Sanghee/Practice1/Practice1/NoticeCell.swift
> +
불필요한 공백

2021-09-17 23:04 UTC, della-padula commented on Sanghee/Practice1/Practice1/ViewController.swift
> +
불필요한 공백으로 보여요

2021-09-18 08:29 UTC, sanghee-dev commented on Sanghee/Practice1/Practice1/DetailController.swift
> +        cell.contentView.isUserInteractionEnabled = false
다운로드 버튼이 눌리지 않아 추가하였습니다

2021-09-19 01:58 UTC, della-padula approved these changes

2021-09-19 01:58 UTC, merged