Feature/jiyun
della-padula/YappUltraHardPractice pull request #50
Opened 2021-09-17 16:49 UTC by glossyyoon

2021-09-17 23:00 UTC, della-padula requested changes
전반적으로 Code 컨벤션이 일관성이 없습니다. 일관성 지켜주시고 다소 변수명을 가볍게 정한 것들이 보이는데 신경 써서 리뷰 사항 답변 및 수정해주세요

2021-09-19 05:01 UTC, glossyyoon commented on Jiyoon/Practice1/Practice1/CollectionCell.swift
> +        self.addSubview(cellTimeLabel)
꼭 필요한 경우에만 사용하도록 하겠습니다!

2021-09-19 05:37 UTC, glossyyoon commented on Jiyoon/Practice1/Practice1/CollectionCell.swift
> +            maker.centerX.equalTo(contentView.safeAreaLayoutGuide.snp.centerX)
superView는 현재 뷰의 부모 뷰를 말하는데 지금은 CollectionCell에서 따로 부모 뷰를 만들지 않고 바로 UILabel을 추가했기 때문에 superView로 centerX를 잡으면 nil이 반환되면서 런타임 에러가 발생합니다.

2021-09-19 05:40 UTC, glossyyoon commented on Jiyoon/Practice1/Practice1/PageViewController.swift
> +    var locationName = UILabel()
넵!

2021-09-19 05:45 UTC, glossyyoon commented on Jiyoon/Practice1/Practice1/PageViewController.swift
> +            maker.centerX.equalTo(view.safeAreaLayoutGuide.snp.centerX)
지금 파일에서는 같습니다! equalToSuperview가 가독성이 좀 더 좋은 것 같아 고쳤습니다.

2021-09-19 05:47 UTC, glossyyoon commented on Jiyoon/Practice1/Practice1/PageViewController.swift
> +            maker.height.equalTo(CGSize(width: 30, height: 30))
CGSize 없애고 Int를 바로 넣어주었습니다!

2021-09-19 05:54 UTC, glossyyoon commented on Jiyoon/Practice1/Practice1/ViewController.swift
> +        present(vc, animated: true, completion: nil)
앗 앞으로 옮겼을 때랑 차이가 있는지 확인해보려고 앞에 넣어봤습니다. 차이는 없는 것으로 확인했고 다시 뒤로 미뤘습니다.

2021-09-19 07:11 UTC, della-padula requested changes
코드 수정 후 커밋 안하고 resolved 했는데 다시 엽니다.

2021-09-19 07:11 UTC, della-padula commented on Jiyoon/Practice1/Practice1/CollectionCell.swift
> +        self.addSubview(cellTimeLabel)
어떤 부분에 필요하고 어떤 부분에 필요하지 않는지 설명해주세요~

2021-09-20 00:35 UTC, della-padula requested changes

2021-09-20 00:35 UTC, della-padula commented on Jiyoon/WeatherApp/WeatherApp/ViewController.swift
> +    var location_eng: [String] = ["Seoul", "Daejeon", "Daegu", "Busan"]
변수명

2021-09-20 00:35 UTC, della-padula commented on Jiyoon/WeatherApp/WeatherApp/ViewController.swift
> +    var tempLow: [String] = []
변수명

2021-09-20 00:35 UTC, della-padula commented on Jiyoon/WeatherApp/WeatherApp/ViewController.swift
> +            let task = session.dataTask(with: url) { (data, response, error) in
요구사항에 Alamofire 쓰라고 했었는데 여기서는 URLSession을 사용한 이유는 무엇인가요?

2021-09-20 00:35 UTC, della-padula commented on Jiyoon/WeatherApp/WeatherApp/ViewController.swift
> +        for locate in location_eng{
띄어쓰기는 기본입니다

2021-09-20 00:35 UTC, della-padula commented on Jiyoon/WeatherApp/WeatherApp/ViewController.swift
> +        for icon in icons{
띄어쓰기

2021-09-20 00:35 UTC, della-padula commented on Jiyoon/WeatherApp/WeatherApp/ViewController.swift
> +        cell.locationLabel.text = self.location[indexPath.row]
cell 내부 뷰에 직접 접근하지 마세요

2021-09-20 00:35 UTC, della-padula commented on Jiyoon/WeatherApp/WeatherApp/Views.swift
> +        var locationName = UILabel()
뷰를 나타내는 변수명인지 일반 프로퍼티인지 구분 안됩니다. 변수명 고민해주세요.

2021-09-20 00:35 UTC, della-padula commented on Jiyoon/WeatherApp/WeatherApp/Views.swift
> +        var tempLow = UILabel()
여기까지 다 변수명 재고해주세요.

2021-09-20 00:35 UTC, della-padula commented on Jiyoon/WeatherApp/WeatherApp/Views.swift
> +        let view = UIView()
view1이라는 변수명은 그냥 아무생각없이 만든 변수명으로 보입니다. 이름 재고해서 다시 변경해주세요.

2021-09-20 00:35 UTC, della-padula commented on Jiyoon/WeatherApp/WeatherApp/Views.swift
> +        var backButton = UIButton()
여기도 다 마찬가지

2021-09-20 00:35 UTC, della-padula commented on Jiyoon/WeatherApp/WeatherApp/WeatherCell.swift
> +        self.locationLabel = UILabel()
여기에서 정의할 필요가 있을까요? 저번 리뷰에도 언급했는데

2021-09-20 00:35 UTC, della-padula commented on Jiyoon/WeatherApp/WeatherApp/WeatherData.swift
> +    let temp_max: Double
Camel Case

2021-09-20 07:21 UTC, glossyyoon commented on Jiyoon/WeatherApp/WeatherApp/CollectionCell.swift
> -        self.cellTimeLabel = UILabel()
선언부로 옮겼습니다

2021-09-20 07:21 UTC, glossyyoon commented on Jiyoon/WeatherApp/WeatherApp/CollectionCell.swift
> -        self.addSubview(cellTempLabel)
클로저나 동일한 변수 명을 사용하였을 경우 등 self를 반드시 써야 하는 경우에만 쓰도록 하겠습니다.

2021-09-20 07:21 UTC, glossyyoon commented on Jiyoon/WeatherApp/WeatherApp/CollectionCell.swift
> -
불필요한 공백 제거

2021-09-20 07:21 UTC, glossyyoon commented on Jiyoon/WeatherApp/WeatherApp/PageViewController.swift
> +    var tempLowLabel = UILabel()
변수명 바꿈

2021-09-20 07:21 UTC, glossyyoon commented on Jiyoon/WeatherApp/WeatherApp/PageViewController.swift
> +            maker.centerX.equalToSuperview()
equalToSuperview와 safeAreaLayout를 사용한 결과가 같아 바꾸었습니다.

2021-09-20 07:21 UTC, glossyyoon commented on Jiyoon/WeatherApp/WeatherApp/PageViewController.swift
> +            maker.width.equalTo(30)
CGSize대신 Int로 바꾸었습니다.

2021-09-20 07:21 UTC, glossyyoon commented on Jiyoon/WeatherApp/WeatherApp/ViewController.swift
> +    var iconsList = [UIImage(systemName: "moon.stars")?.withTintColor(.white),
변수명 바꿈

2021-09-20 07:21 UTC, glossyyoon commented on Jiyoon/WeatherApp/WeatherApp/ViewController.swift
> +            }
먼저 데이터를 fetch해온 다음 뷰에 반영하기 위해 DispatchQueue를 추가하였는데 하기 전과 같은것 같습니다. 앱이 로딩 된 후 1~2초 정도 지난 후에 fetch가 끝납니다.

2021-09-20 07:21 UTC, glossyyoon commented on Jiyoon/WeatherApp/WeatherApp/ViewController.swift
> +//        cell.tempLabel.text = "\(tempList[indexPath.row])°C"
에러가 나서 잠시 주석처리 해두었습니다.

2021-09-20 07:21 UTC, glossyyoon commented on Jiyoon/WeatherApp/WeatherApp/WeatherData.swift
> +    let temp_max: Double
JSON에서 받아오는 데이터 명이 temp_min, temp_max라 카멜케이스로 변경하지 못하였습니다.

2021-09-20 07:21 UTC, glossyyoon commented on Jiyoon/WeatherApp/WeatherApp/CollectionCell.swift
> +        self.cellWeatherIcon.image = UIImage(systemName: "sun.max.fill")?.withTintColor(.yellow)
미리 셀에 대한 모델 정의를 여기서 해주었습니다. 다만 indexPath.row를 받아와야 하는 cellTimeLabel같은 경우에는 indexPath를 어떻게 받아와야할지 모르겠어서 우선 times[0]으로 처리해 두었습니다.

2021-09-21 02:42 UTC, della-padula commented on Jiyoon/WeatherApp/WeatherApp/ViewController.swift
> +            }
데이터를 fetch한 후에 클로저로 처리하는게 더 안전할 것 같네요

2021-09-22 11:27 UTC, della-padula requested changes

2021-09-22 11:27 UTC, della-padula commented on Jiyoon/WeatherApp/WeatherApp/CollectionCell.swift
> +        self.cellWeatherIcon.image = UIImage(systemName: "sun.max.fill")?.withTintColor(.yellow)
indexPath는 dataSource 리스트에서 아이템을 찾기 위한 index로 사용하는 것입니다. 별도의 데이터(리스트)를 저장하고 있어야 하고 이 데이터 리스트 속 아이템(index로 접근)을 셀에 넣어주면 셀은 그 데이터를 알아서 뷰에 적용하도록 구현해야 합니다.

2021-09-23 17:56 UTC, glossyyoon commented on Jiyoon/WeatherApp/WeatherApp/PageViewController.swift
> +        cell.cellTimeLabel.text = timeList[indexPath.row]
timeList라는 모델을 따로 만들어서 거기서 indexPath.row를 통해 데이터를 가져오도록 하였습니다!

2021-09-23 17:56 UTC, glossyyoon commented on Jiyoon/WeatherApp/WeatherApp/ViewController.swift
> +            tableView.reloadData()
fetch 한 후에 sync로 reload tableView를 하였습니다.

2021-09-24 04:43 UTC, della-padula commented on Jiyoon/WeatherApp/WeatherApp/ViewController.swift
> +            tableView.reloadData()
closure로는 어렵나요? escaping closure로 DispatchQueue 안쓰고 해보세요

2021-09-24 11:35 UTC, glossyyoon commented on Jiyoon/WeatherApp/WeatherApp/ViewController.swift
> +            }
@escaping 써서 처리했습니다!

2021-09-24 11:40 UTC, della-padula approved these changes

2021-09-24 13:06 UTC, merged