Feature/byeongyun coredata
della-padula/YappUltraHardPractice pull request #63
Opened 2021-09-24 20:04 UTC by ITlearning

코어 데이터 기초 공부 후 PR 올립니다.

2021-09-24 23:22 UTC, della-padula requested changes
빠른 시간 내에 학습 후 적용 아주 좋습니다. 수정 사항만 수정해주시면 될 것 같습니다.

2021-09-24 23:22 UTC, della-padula commented on Byeongyun/Practice1/Practice1/View/MainViewController.swift
> +import CoreData
import는 오름차순으로 정렬

2021-09-24 23:22 UTC, della-padula commented on Byeongyun/Practice1/Practice1/View/MainViewController.swift
> +        //let endIndex = IndexPath(row: 0, section: 0)
안쓰는 함수면 지워주시면 됩니다

2021-09-24 23:22 UTC, della-padula commented on Byeongyun/Practice1/Practice1/View/MainViewController.swift
>      let tableView = UITableView(frame: CGRect(x: 0, y: 0, width: 400, height: 400))
private

2021-09-24 23:22 UTC, della-padula commented on Byeongyun/Practice1/Practice1/View/MainViewController.swift
>          let cell = tableView.dequeueReusableCell(withIdentifier: FeedTableViewCell.cellId, for: indexPath) as! FeedTableViewCell
강제 언래핑은 위험하므로 if let 등으로 처리

2021-09-24 23:22 UTC, della-padula commented on Byeongyun/Practice1/Practice1/View/PlusViewController.swift
> +        //selectImage = UIImage(data: (feedContact?.uploadImage!)!)!
안쓰는 코드는 지워주세요

2021-09-24 23:22 UTC, della-padula commented on Byeongyun/Practice1/Practice1/View/PlusViewController.swift
> +    private lazy var selectedImageViewer: UIImageView = {
lazy var 안써도 무관할 것 같은데 lazy var를 사용한 이유가 무엇인가요?

2021-09-24 23:22 UTC, della-padula commented on Byeongyun/Practice1/Practice1/View/UserViewController.swift
>      let cellId = "userViewCell"
이거 안쓰는 것으로 보이는데 제거하는게 좋을 것 같네요, 만약 사용한다면 적절한 위치에 재정의해주세요.

2021-09-25 02:28 UTC, ITlearning commented on Byeongyun/Practice1/Practice1/View/PlusViewController.swift
> +    private lazy var selectedImageViewer: UIImageView = {
저번에 StackView에서 사용한 것과 마찬가지로 동일한 클래스 내에 선언된 프로퍼티를 사용하기 위해서 lazy를 사용하였습니다.
개선할 수 있는지 더 찾아보도록 하겠습니다.

2021-09-25 04:09 UTC, della-padula approved these changes

2021-09-25 04:09 UTC, merged